name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup os
        run: sudo apt-get install libmagick++-dev libcurl4-openssl-dev libxml2-dev -y
      - name: Setup r
        uses: r-lib/actions/setup-r@v1
      - name: Install dependencies
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()
        shell: Rscript {0}
      - name: Run lint
        run: lintr::lint_dir("src")
        shell: Rscript {0}
